# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-07-17 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Country Code')),
                ('name', models.CharField(max_length=60, verbose_name='Country Name')),
                ('continent', models.CharField(choices=[('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('Africa', 'Africa'), ('Oceania', 'Oceania'), ('Antarctica', 'Antarctica'), ('South America', 'South America')], default='Asia', max_length=20)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('matchId', models.AutoField(primary_key=True, serialize=False)),
                ('matchDate', models.DateField()),
            ],
            options={
                'db_table': 'matches',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('imageURL', models.URLField(max_length=500)),
                ('jerse_number', models.IntegerField()),
                ('countryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Country')),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='PlayerHistory',
            fields=[
                ('historyId', models.AutoField(primary_key=True, serialize=False)),
                ('matches', models.IntegerField(default=0)),
                ('run', models.IntegerField(default=0)),
                ('highest_score', models.IntegerField(default=0)),
                ('fifties', models.IntegerField(default=0)),
                ('hundreds', models.IntegerField(default=0)),
                ('playerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Player')),
            ],
            options={
                'db_table': 'player_history',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=50)),
                ('logoURL', models.URLField(max_length=500)),
                ('clubState', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='teamId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Team'),
        ),
        migrations.AddField(
            model_name='matches',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='cricket.Team'),
        ),
        migrations.AddField(
            model_name='matches',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='cricket.Team'),
        ),
        migrations.AddField(
            model_name='matches',
            name='winerTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winerTeam', to='cricket.Team'),
        ),
    ]
